(function(){
var LANG_KEY = 'bizforum_lang';
var I18N = {
ru: {
  navCategories: 'Темы', navFavorites: 'Избранное', navNewPost: 'Новый пост',
  searchPlaceholder: 'Поиск...', searchBtn: 'Найти',
  authRegistry: 'Реестр', navVerification: 'Верификация', authLogin: 'Войти', authRegister: 'Регистрация', authProfile: 'Профиль', authLogout: 'Выйти',
  sidebarCategories: 'Темы', sidebarFavorites: 'Избранное', sidebarDrafts: 'Мои черновики', sidebarNewPost: 'Новый пост', sidebarTrending: 'В тренде', navDrafts: 'Мои черновики', postSaveDraft: 'Сохранить черновик', emptyStateDrafts: 'Нет черновиков', emptyStateDraftsDesc: 'Сохраняйте посты как черновики при создании — они появятся здесь.', publishDraft: 'Опубликовать',
  welcomeBanner: 'Добро пожаловать в @Bizz! Обсуждайте темы, оставляйте комментарии и находите единомышленников.',
  sharePost: 'Поделиться', filterMyPosts: 'Мои посты', shortcutsTitle: 'Горячие клавиши', shortcutSubmitComment: 'Ctrl+Enter — отправить', shortcutCancelReply: 'Escape — отменить ответ', shortcutCloseModal: 'Escape — закрыть', draftAutoSaved: 'Черновик сохранён', draftRestored: 'Черновик восстановлен',
  emptyStateFeed: 'Пока нет обсуждений', emptyStateFeedDesc: 'Создайте первый пост — нажмите «Новый пост» в меню.',
  emptyStateFav: 'В избранном пусто', emptyStateFavDesc: 'Отмечайте посты звёздочкой, чтобы сохранить их сюда.',
  emptyStateSearch: 'Ничего не найдено', emptyStateSearchDesc: 'Попробуйте другой запрос или категорию.',
  feedDiscussions: 'Обсуждения', feedFeedAll: 'Все', feedFeedFollowing: 'Подписки', feedSortLabel: 'Сортировка:', feedSortRecommended: 'Рекомендуемое', feedSortNew: 'Новые посты', feedSortHot: 'Популярные', feedSortComments: 'По комментариям', feedSortViews: 'По просмотрам',
  loadMore: 'Ещё', feedNoPosts: 'Пока нет обсуждений.',
  all: 'Все', category: 'Категория',
  views: 'просмотров', commentsShort: 'коммент.', favTitle: 'В избранное',
  reaction: 'Реакция', reactions: 'Реакции',
  back: '← Назад', backToFeed: 'Назад к ленте', backToCategory: 'Назад в категорию', backToFavorites: 'Назад в избранное', backToSearch: 'Назад к поиску', readMore: 'Открыть', comments: 'Комментарии', leaveComment: 'Оставить комментарий', commentPlaceholder: 'Написать комментарий...', commentSubmit: 'Отправить',
  commentEdit: 'Изменить', commentEdited: 'изменено', commentDelete: 'Удалить', commentDeleteAdmin: 'Удалить (админ)', commentReply: 'Ответить', replyTo: 'Ответ на', commentsSort: 'Сортировка:', commentsSortNew: 'Сначала новые', commentsSortOld: 'Сначала старые', commentsSortUseful: 'По полезности', commentsNewReplies: 'новых', commentVerifiedOnly: 'Оставить комментарий могут только верифицированные пользователи.', commentVerificationHint: 'Подтвердите почту, чтобы комментировать.', reactionVerifiedOnly: 'Ставить реакции могут только верифицированные пользователи.', friendsVerifiedOnly: 'Отправлять и принимать заявки в друзья могут только верифицированные пользователи.', bestAnswer: 'Лучший ответ', markAsBestAnswer: 'Отметить как решение', unmarkBestAnswer: 'Отменить решение',
  noComments: 'Пока нет комментариев.', noCommentsInvite: 'Оставьте комментарий в форме ниже.', loading: 'Загрузка...',
  adminEditPost: 'Изменить пост', adminDeletePost: 'Удалить пост',
  dash: '—', commentsCount: 'комментариев',
  breadcrumbHome: 'Главная', breadcrumbCategories: 'Темы', breadcrumbFavorites: 'Избранное', breadcrumbNewPost: 'Новый пост', breadcrumbProfile: 'Профиль', breadcrumbRegistry: 'Реестр',
  pageCategories: 'Темы', pageNewPost: 'Новый пост', pageEditPost: 'Редактировать пост', pageProfile: 'Мой профиль', pageRegistry: 'Реестр аккаунтов', pageVerification: 'Верификация',
  favEmpty: 'В избранном пока ничего нет.',
  postCategory: 'Категория', postTitle: 'Заголовок', postMediaUrls: 'Фото или видео (URL)', postTitlePlaceholder: 'О чём пост?', postBody: 'Текст', postBodyPlaceholder: 'Опишите вопрос или тему...', postAuthor: 'Автор', postAnonymousLabel: 'Опубликовать анонимно', postAnonymousHint: 'Автор не будет указан, пост не появится в вашем профиле.', postPublish: 'Опубликовать', postSave: 'Сохранить', postDeleted: 'Пост удалён', createPostLoginRequired: 'Войдите в аккаунт, чтобы создать пост.',
  profileEdit: 'Редактировать данные', profileFirstName: 'Имя', profileLastName: 'Фамилия', profileCompany: 'Компания', profilePhoto: 'Фото (URL)', profileDob: 'Дата рождения', profileSave: 'Сохранить',
  profileVerification: 'Верификация', profileVerified: 'Верифицирован', profilePending: 'Ожидает проверки', profileStats: 'Активность', profilePostsCount: 'Постов', profileCommentsCount: 'Комментариев', profileReactionsReceived: 'Реакций получено', profileTotalViews: 'Просмотров', profileHelpfulCount: 'Полезных ответов', profileCompanyStage: 'Этап компании', profileCompanyStageIdea: 'Идея', profileCompanyStageStartup13: 'Стартап 1–3 года', profileCompanyStageStartup35: 'Стартап 3–5 лет', profileCompanyStageGrowth: 'Рост', profileCompanyStageEnterprise: 'Крупный бизнес', profileCompanyStageOther: 'Другое', profileBadges: 'Бейджи', profileSubscribers: 'Подписчиков', profileChangePassword: 'Сменить пароль', profileCurrentPassword: 'Текущий пароль', profileNewPassword: 'Новый пароль', profileConfirmPassword: 'Подтвердите новый пароль', profileMfa: 'Двухфакторная аутентификация', profileMfaDesc: 'При включении 2FA при каждом входе на почту будет отправляться код, который нужно ввести.', profileMfaEnabled: '2FA включена', profileMfaCodeSent: 'Код отправлен на почту', profileMfaEnterCode: 'Введите код из письма', authMfaCode: 'Код из письма', authMfaCodePlaceholder: '6 цифр',
  profileTabPersonal: 'Личные данные', profileTabSecurity: 'Безопасность', profileTabAchievements: 'Достижения', profileTabStatistics: 'Статистика',
  profileDeleteAccount: 'Удалить аккаунт', profileDeleteAccountHint: 'Удаление аккаунта необратимо. Все ваши посты, комментарии и данные будут удалены.', profileDeleteAccountConfirm: 'Вы уверены? Удаление аккаунта необратимо.', profileDeleteAccountConfirm2: 'Это последнее предупреждение. Действительно удалить аккаунт?', profileStatistics: 'Статистика автора', profileStatsUnavailable: 'Статистика недоступна', profileStatsNoData: 'Нет данных за период', profileStatsChartHint: 'Просмотры по постам (по дате публикации)', profileStatsSummary: 'Сводка', profileStatsChartTitle: 'Динамика просмотров', profileStatsAvgPerPost: 'В среднем на пост', profileStatsWordViews: 'просмотров', profileStatsWordReactions: 'реакций',
  adminPanelTitle: 'Панель управления', adminPanelRegistryDesc: 'Аккаунты пользователей', adminPanelVerificationDesc: 'Заявки на верификацию', adminPanelReportsDesc: 'Модерация жалоб', adminPanelChatDesc: 'Сообщения пользователей', adminPanelContentDesc: 'Посты и модерация', adminContent: 'Контент', adminContentHint: 'Последние посты. Откройте пост для редактирования или удаления (нужен включённый режим админа).', adminStatsUsers: 'Пользователей', adminStatsPosts: 'Постов', adminStatsComments: 'Комментариев', adminStatsUnverified: 'На верификации', adminStatsNewToday: 'Новых за сегодня', adminStatsAdminChats: 'Обращений в админ', adminRecentUsers: 'Новые пользователи', adminRecentPosts: 'Последние посты', adminModeOn: 'Admin: вкл', adminModeOff: 'Admin off',
adminReports: 'Жалобы', adminReportsPending: 'Ожидают', adminReportsReviewed: 'На рассмотрении', adminReportsAll: 'Все', adminReportsNone: 'Нет жалоб', adminReportsResolve: 'Закрыть', adminReportsDismiss: 'Отклонить', reportTargetPost: 'пост', reportTargetComment: 'комментарий',
  adminEdit: 'Редактирование', adminNoAccounts: 'Нет аккаунтов.', adminEditBtn: 'Редактировать',
  verificationHint: 'Одобрите или отклоните заявки. При отклонении профиль пользователя удаляется.',
  verificationApprove: 'Одобрить', verificationReject: 'Отклонить', verificationRejectConfirm: 'Отклонить заявку? Профиль пользователя будет удалён.', verificationNone: 'Нет заявок на верификацию.',
  authTabLogin: 'Вход', authTabRegister: 'Регистрация', authEmail: 'Почта', authPassword: 'Пароль', authFirstName: 'Имя', authLastName: 'Фамилия', authCompany: 'Компания', authPasswordConfirm: 'Подтверждение пароля', authPasswordRepeat: 'Повторите пароль', authPasswordRules: 'От 8 символов, заглавные, строчные, спецсимволы', authPwMin8: 'Минимум 8 символов', authPwUpper: 'Заглавная буква', authPwLower: 'Строчная буква', authPwSpecial: 'Специальный символ (!@#$% и т.п.)', authSecretWord: 'Секретное слово', authSecretPlaceholder: 'Ваше слово для важных моментов', authSubmitRegister: 'Зарегистрироваться', registerSuccessMessage: 'Регистрация прошла успешно. Проверьте почту — мы отправили ссылку для подтверждения. После подтверждения войдите в аккаунт.',
  searchResults: 'Результаты поиска', searchFor: 'По запросу «{q}»: {n}',
  pageFriends: 'Знакомства', navGroups: 'Группы', groupsSearchTitle: 'Поиск групп', groupsSearchPlaceholder: 'Поиск групп...', groupsNoResults: 'Нет открытых групп', groupsSearchHint: 'Войдите в аккаунт для поиска групп.', groupOpen: 'Открытая', groupMembers: 'участников', groupJoin: 'Вступить', groupRequestSent: 'Заявка отправлена', groupOpenLabel: 'Открытая группа', groupOpenHint: 'Другие смогут найти группу и подать заявку на вступление.', groupDescription: 'Описание', groupCategory: 'Категория', groupJoinRequests: 'Заявки на вступление', groupJoinRequestsNone: 'Нет заявок.',
  friendsSearchLabel: 'Найти человека', friendsSearchPlaceholder: 'Введите имя, фамилию или компанию', friendsIncoming: 'Заявки вам', friendsIncomingNone: 'Нет входящих заявок.', friendsAccept: 'Принять', friendsReject: 'Отклонить', friendsAdd: 'Добавить в друзья', friendsSent: 'Отправлено', friendsAlready: 'Вы друзья', friendsRemove: 'Удалить из друзей', friendsRemoveConfirm: 'Удалить из друзей?', friendsSubscribe: 'Подписаться', friendsSubscribed: 'Подписано', friendsNoResults: 'Никого не найдено.', friendsSearchHint: 'Доступно при входе в аккаунт.', friendsLoadMore: 'Ещё', friendsPostsCount: 'постов', friendsViewsCount: 'просмотров', friendsDirectory: 'Люди на платформе',
  userProfilePosts: 'Посты участника', landingHeadline: 'Сила предпринимателей', landingJoinToday: 'В одном сайте для тебя', landingRegisterWithGoogle: 'Зарегистрироваться с Google', landingRegisterWithApple: 'Зарегистрироваться с Apple ID', landingOr: 'или', landingRegister: 'Зарегистрироваться', landingTerms: 'Регистрируясь, вы соглашаетесь с Условиями предоставления услуг и Политикой конфиденциальности.', landingAlreadyRegistered: 'Уже зарегистрированы?', landingLogIn: 'Войти', landingPreviewTitle: 'Как может выглядеть твой опыт на сайте',
  promptEditComment: 'Изменить комментарий:', confirmDeleteComment: 'Удалить комментарий?', confirmDeleteCommentAdmin: 'Удалить комментарий? (админ)', confirmDeletePost: 'Удалить пост? (админ)', confirmDeleteOwnPost: 'Удалить пост? Действие нельзя отменить.', confirmLeaveNewPost: 'Пост не сохранён. Уйти?', promptTitle: 'Заголовок', promptBody: 'Текст',
  error: 'Ошибка', errorPasswordsMatch: 'Пароли не совпадают', errorPasswordLength: 'Пароль: от 8 символов, заглавные, строчные, спецсимволы', errorEmailRequired: 'Введите email', errorEmailInvalid: 'Введите корректный email', successPasswordChanged: 'Пароль изменён', successEmailChanged: 'Email изменён. Проверьте почту.',
  footerText: '@Bizz — площадка для общения и поддержки предпринимателей.', feedComposerPrompt: 'Чем хотите поделиться?', footerRights: 'Все права защищены.', footerPrivacy: 'Политика конфиденциальности', privacyIntro: '@Bizz собирает и обрабатывает данные пользователей в соответствии с законодательством. Мы используем данные для работы платформы, верификации и связи с вами.',
  chatsTitle: 'Чаты', chatsAdmin: 'Администрация', chatsAdminDesc: 'Уведомления: ответы на ваши сообщения, комментарии к постам, верификация, заявки в друзья.', chatsAdminNotes: 'Заметка для администрации', chatsAdminNotesPlaceholder: 'Написать сообщение или заметку...', chatsRecent: 'Недавние', chatsGroups: 'Групповые чаты', chatsCreateGroup: '+ Создать группу', chatsGroupTitle: 'Название чата', chatsSelectFriends: 'Выберите друзей', chatsSearchFriend: 'Поиск по имени или компании...', chatsNoResults: 'Ничего не найдено', chatsRemoveMember: 'Удалить', chatsFriends: 'Друзья', chatsNoFriends: 'Пока нет друзей. Добавьте в разделе Знакомства.', chatsNoMessages: 'Нет сообщений. Напишите первым!', chatsYou: 'Вы', chatsMessagePlaceholder: 'Написать сообщение...', chatsAI: 'Чат с ИИ', chatsSoon: 'скоро', chatsAISoon: 'Скоро здесь можно будет общаться с нейросетью.',
  notification_mention: 'Вас упомянули в комментарии', notification_comment_on_post: 'Комментарий к вашему посту', notification_reply_to_comment: 'Ответ на ваш комментарий', notification_verification_approved: 'Верификация одобрена', notification_friend_request: 'Заявка в друзья', notification_registration: 'Добро пожаловать! Регистрация прошла успешно.', notification_message_reply: 'Ответ на ваше сообщение в чате', notification_moderation_post: 'Модерация поста: исправьте недопустимые слова',
  reactionMuzhik: 'мужик!', reactionKoroleva: 'королева!', reactionRzhaka: 'ржаакаа', reactionFire: 'огонь', reactionFu: 'фу', reactionGrustno: 'грустно', reactionBabki: 'делаем бабки', reactionHahaha: 'хахаха', reactionUseful: 'Полезно',
  balance: 'баланс', postPrice: 'Цена поста (валюта)', postPriceHint: 'Только для категории «Полезное». 0 = бесплатный пост.', buyPost: 'Купить', profileBalance: 'Баланс', adminAddBalance: 'Добавить валюту', adminAddBalanceBtn: 'Добавить', balanceTopUpTitle: 'Пополнить баланс', balanceTopUpHint: 'Пополните баланс для покупки платных постов.', balanceTopUpHintText: 'Введите количество монет. 1 монета = 1 ₽. Платёжная система будет подключена позже.', balanceTopUpAmount: 'Количество монет', balanceTopUpBuy: 'Купить', balanceTopUpMin: 'Минимум 1 монета', balanceTopUpSuccess: 'Баланс пополнен!',
  navSubscription: 'Подписка', subscriptionTitle: 'Подписка безлимит', subscriptionDesc: 'Читай все посты без ограничений. 2 бесплатных поста в месяц — этого мало? Подключай безлимит.', subscriptionPrice: 'Оплата — скоро', subscriptionBuy: 'Подключить', subscriptionOpen: 'Открыть', subscriptionOpensLeft: 'осталось', subscriptionConnectUnlimited: 'Подключить тариф безлимит', subscriptionOutOfOpens: 'Вы использовали все бесплатные открытия в этом месяце. Подключите тариф безлимит.', adminSubscriptionEnds: 'Подписка до', subscriptionBadge: 'Безлимит', subscriptionHeroTitle: 'Читайте всё. Без ограничений.', subscriptionHeroDesc: 'Откройте доступ к сотням обсуждений от предпринимателей — опыт, инсайты и решения, которые работают.', subscriptionBenefit1Title: 'Неограниченный доступ', subscriptionBenefit1Text: 'открывайте любой пост, в любой момент', subscriptionBenefit2Title: 'Эксклюзивный опыт', subscriptionBenefit2Text: 'идеи от тех, кто уже добился успеха', subscriptionBenefit3Title: 'Сообщество', subscriptionBenefit3Text: 'обсуждайте и находите единомышленников', subscriptionBenefit4Title: 'Группы', subscriptionBenefit4Text: 'создавайте группы для общения с предпринимателями', subscriptionPopular: 'Популярный выбор', subscriptionPriceOld: '813 ₽', subscriptionPricePeriod: 'в месяц', subscriptionDiscount: '−15%', subscriptionMarketing: '1 месяц в подарок не дарим — мы ценим свою платформу и развиваем её!', subscriptionActivated: 'Подписка активирована на месяц!', subscriptionNote: 'Оплата будет доступна скоро.', subscriptionCtaText: 'Присоединяйтесь к предпринимателям, которые уже развивают свой бизнес вместе с @Bizz', toastModerationTitle: 'Модерация', toastModerationText: 'Пост сохранён как черновик. Обнаружены недопустимые слова: ',
  tourClose: 'Закрыть', tourBack: 'Назад', tourNext: 'Далее', tourOf: 'из', tourFinish: 'Закрыть',
  tourWelcomeTitle: 'Добро пожаловать в @Bizz!', tourWelcomeText: 'Краткий обзор интерфейса: покажем основные разделы и кнопки.',
  tourStepLogoTitle: 'Главная', tourStepLogoText: 'Логотип — нажмите, чтобы вернуться в ленту.',
  tourStepNavTitle: 'Разделы', tourStepNavText: 'Темы, избранное, подписка и чаты.',
  tourStepSidebarTitle: 'Боковая панель', tourStepSidebarText: 'Темы постов, тренды, избранное, черновики и кнопка «Новый пост».',
  tourStepFeedTitle: 'Лента и публикация', tourStepFeedText: 'Здесь лента обсуждений. Сверху — блок для быстрой публикации поста.',
  tourStepProfileTitle: 'Профиль', tourStepProfileText: 'Ваше имя, баланс, переход в профиль и выход из аккаунта.',
  tourEndTitle: 'Готово!', tourEndText: 'Можете начать с просмотра ленты или написать первый пост. Удачи!'
},
en: {
  navCategories: 'Topics', navFavorites: 'Favorites', navNewPost: 'New post',
  searchPlaceholder: 'Search...', searchBtn: 'Search',
  authRegistry: 'Registry', navVerification: 'Verification', authLogin: 'Log in', authRegister: 'Register', authProfile: 'Profile', authLogout: 'Log out',
  sidebarCategories: 'Topics', sidebarFavorites: 'Favorites', sidebarDrafts: 'My drafts', sidebarNewPost: 'New post', sidebarTrending: 'Trending', navDrafts: 'My drafts', postSaveDraft: 'Save draft', emptyStateDrafts: 'No drafts', emptyStateDraftsDesc: 'Save posts as drafts when creating — they will appear here.', publishDraft: 'Publish',
  welcomeBanner: 'Welcome to @Bizz! Discuss topics, leave comments, and find like-minded people.',
  sharePost: 'Share', filterMyPosts: 'My posts', shortcutsTitle: 'Keyboard shortcuts', shortcutSubmitComment: 'Ctrl+Enter — submit', shortcutCancelReply: 'Escape — cancel reply', shortcutCloseModal: 'Escape — close', draftAutoSaved: 'Draft saved', draftRestored: 'Draft restored',
  emptyStateFeed: 'No discussions yet', emptyStateFeedDesc: 'Create the first post — click «New post» in the menu.',
  emptyStateFav: 'Favorites is empty', emptyStateFavDesc: 'Star posts to save them here.',
  emptyStateSearch: 'Nothing found', emptyStateSearchDesc: 'Try a different query or category.',
  feedDiscussions: 'Discussions', feedFeedAll: 'All', feedFeedFollowing: 'Following', feedSortLabel: 'Sort:', feedSortRecommended: 'Recommended', feedSortNew: 'New posts', feedSortHot: 'Popular', feedSortComments: 'By comments', feedSortViews: 'By views',
  loadMore: 'More', feedNoPosts: 'No discussions yet.',
  all: 'All', category: 'Category',
  views: 'views', commentsShort: 'comments', favTitle: 'Add to favorites',
  reaction: 'Reaction', reactions: 'Reactions',
  back: '← Back', backToFeed: 'Back to feed', backToCategory: 'Back to category', backToFavorites: 'Back to favorites', backToSearch: 'Back to search', readMore: 'Open', comments: 'Comments', leaveComment: 'Leave a comment', commentPlaceholder: 'Write a comment...', commentSubmit: 'Submit',
  commentEdit: 'Edit', commentEdited: 'edited', commentDelete: 'Delete', commentDeleteAdmin: 'Delete (admin)', commentReply: 'Reply', replyTo: 'Reply to', commentsSort: 'Sort:', commentsSortNew: 'Newest first', commentsSortOld: 'Oldest first', commentsSortUseful: 'By usefulness', commentsNewReplies: 'new', commentVerifiedOnly: 'Only verified users can leave comments.', commentVerificationHint: 'Verify your email to comment.', reactionVerifiedOnly: 'Only verified users can add reactions.', friendsVerifiedOnly: 'Only verified users can send or accept friend requests.', bestAnswer: 'Best answer', markAsBestAnswer: 'Mark as solution', unmarkBestAnswer: 'Unmark solution',
  noComments: 'No comments yet.', noCommentsInvite: 'Leave a comment in the form below.', loading: 'Loading...',
  adminEditPost: 'Edit post', adminDeletePost: 'Delete post',
  dash: '—', commentsCount: 'comments',
  breadcrumbHome: 'Home', breadcrumbCategories: 'Topics', breadcrumbFavorites: 'Favorites', breadcrumbNewPost: 'New post', breadcrumbProfile: 'Profile', breadcrumbRegistry: 'Registry',
  pageCategories: 'Topics', pageNewPost: 'New post', pageEditPost: 'Edit post', pageProfile: 'My profile', pageRegistry: 'Account registry', pageVerification: 'Verification',
  favEmpty: 'Nothing in favorites yet.',
  postCategory: 'Category', postTitle: 'Title', postMediaUrls: 'Photos or videos (URL)', postTitlePlaceholder: 'What is this post about?', postBody: 'Text', postBodyPlaceholder: 'Describe your question or topic...', postAuthor: 'Author', postAnonymousLabel: 'Publish anonymously', postAnonymousHint: 'Author will not be shown, post will not appear on your profile.', postPublish: 'Publish', postSave: 'Save', postDeleted: 'Post deleted', createPostLoginRequired: 'Log in to create a post.',
  profileEdit: 'Edit profile', profileFirstName: 'First name', profileLastName: 'Last name', profileCompany: 'Company', profilePhoto: 'Photo (URL)', profileDob: 'Date of birth', profileSave: 'Save',
  profileVerification: 'Verification', profileVerified: 'Verified', profilePending: 'Pending verification', profileStats: 'Activity', profilePostsCount: 'Posts', profileCommentsCount: 'Comments', profileReactionsReceived: 'Reactions received', profileTotalViews: 'Views', profileHelpfulCount: 'Helpful answers', profileCompanyStage: 'Company stage', profileCompanyStageIdea: 'Idea', profileCompanyStageStartup13: 'Startup 1–3 yrs', profileCompanyStageStartup35: 'Startup 3–5 yrs', profileCompanyStageGrowth: 'Growth', profileCompanyStageEnterprise: 'Enterprise', profileCompanyStageOther: 'Other', profileBadges: 'Badges', profileSubscribers: 'Followers', profileChangePassword: 'Change password', profileCurrentPassword: 'Current password', profileNewPassword: 'New password', profileConfirmPassword: 'Confirm new password', profileMfa: 'Two-factor authentication', profileMfaDesc: 'When 2FA is on, a code will be sent to your email each time you log in.', profileMfaEnabled: '2FA enabled', profileMfaCodeSent: 'Code sent to your email', profileMfaEnterCode: 'Enter the code from the email', authMfaCode: 'Code from email', authMfaCodePlaceholder: '6 digits', profileChangeEmail: 'Change email', profileNewEmail: 'New email',
  profileTabPersonal: 'Personal', profileTabSecurity: 'Security', profileTabAchievements: 'Achievements', profileTabStatistics: 'Statistics',
  profileDeleteAccount: 'Delete account', profileDeleteAccountHint: 'Account deletion is irreversible. All your posts, comments and data will be removed.', profileDeleteAccountConfirm: 'Are you sure? Deletion is irreversible.', profileDeleteAccountConfirm2: 'Last warning. Really delete account?', profileStatistics: 'Author statistics', profileStatsUnavailable: 'Statistics unavailable', profileStatsNoData: 'No data for the period', profileStatsChartHint: 'Views by post (by publish date)', profileStatsSummary: 'Summary', profileStatsChartTitle: 'Views over time', profileStatsAvgPerPost: 'Average per post', profileStatsWordViews: 'views', profileStatsWordReactions: 'reactions',
  adminPanelTitle: 'Admin panel', adminPanelRegistryDesc: 'User accounts', adminPanelVerificationDesc: 'Verification requests', adminPanelReportsDesc: 'Moderate reports', adminPanelChatDesc: 'User messages', adminPanelContentDesc: 'Posts and moderation', adminContent: 'Content', adminContentHint: 'Recent posts. Open a post to edit or delete (admin mode must be on).', adminStatsUsers: 'Users', adminStatsPosts: 'Posts', adminStatsComments: 'Comments', adminStatsUnverified: 'Unverified', adminStatsNewToday: 'New today', adminStatsAdminChats: 'Admin chats', adminRecentUsers: 'Recent users', adminRecentPosts: 'Recent posts', adminModeOn: 'Admin: on', adminModeOff: 'Admin off',
adminReports: 'Reports', adminReportsPending: 'Pending', adminReportsReviewed: 'Under review', adminReportsAll: 'All', adminReportsNone: 'No reports', adminReportsResolve: 'Resolve', adminReportsDismiss: 'Dismiss', reportTargetPost: 'post', reportTargetComment: 'comment',
  adminEdit: 'Edit', adminNoAccounts: 'No accounts.', adminEditBtn: 'Edit',
  verificationHint: 'Approve or reject applications. Rejecting will delete the user profile.',
  verificationApprove: 'Approve', verificationReject: 'Reject', verificationRejectConfirm: 'Reject application? User profile will be deleted.', verificationNone: 'No verification requests.',
  authTabLogin: 'Log in', authTabRegister: 'Register', authEmail: 'Email', authPassword: 'Password', authFirstName: 'First name', authLastName: 'Last name', authCompany: 'Company', authPasswordConfirm: 'Confirm password', authPasswordRepeat: 'Repeat password', authPasswordRules: '8+ chars, upper, lower, special', authPwMin8: 'Min 8 characters', authPwUpper: 'Uppercase letter', authPwLower: 'Lowercase letter', authPwSpecial: 'Special character (!@#$ etc.)', authSecretWord: 'Secret word', authSecretPlaceholder: 'Your word for important moments', authSubmitRegister: 'Register', registerSuccessMessage: 'Registration successful. Check your email — we sent a confirmation link. Log in after confirming.',
  searchResults: 'Search results', searchFor: 'For «{q}»: {n}',
  pageFriends: 'Friends', navGroups: 'Groups', groupsSearchTitle: 'Search groups', groupsSearchPlaceholder: 'Search groups...', groupsNoResults: 'No open groups', groupsSearchHint: 'Sign in to search groups.', groupOpen: 'Open', groupMembers: 'members', groupJoin: 'Join', groupRequestSent: 'Request sent', groupOpenLabel: 'Open group', groupOpenHint: 'Others can find the group and request to join.', groupDescription: 'Description', groupCategory: 'Category', groupJoinRequests: 'Join requests', groupJoinRequestsNone: 'No requests.',
  friendsSearchLabel: 'Find a person', friendsSearchPlaceholder: 'Enter name, surname or company', friendsIncoming: 'Requests for you', friendsIncomingNone: 'No incoming requests.', friendsAccept: 'Accept', friendsReject: 'Decline', friendsAdd: 'Add as friend', friendsSent: 'Sent', friendsAlready: 'You are friends', friendsRemove: 'Remove from friends', friendsRemoveConfirm: 'Remove from friends?', friendsSubscribe: 'Subscribe', friendsSubscribed: 'Subscribed', friendsNoResults: 'No results.', friendsSearchHint: 'Available when signed in.', friendsLoadMore: 'More', friendsPostsCount: 'posts', friendsViewsCount: 'views', friendsDirectory: 'People on the platform',
  userProfilePosts: 'User posts', landingHeadline: 'Power of entrepreneurs', landingJoinToday: 'All in one place for you', landingRegisterWithGoogle: 'Sign up with Google', landingRegisterWithApple: 'Sign up with Apple ID', landingOr: 'or', landingRegister: 'Sign up', landingTerms: 'By signing up, you agree to the Terms of Service and Privacy Policy.', landingAlreadyRegistered: 'Already have an account?', landingLogIn: 'Log in', landingPreviewTitle: 'What your experience could look like',
  promptEditComment: 'Edit comment:', confirmDeleteComment: 'Delete comment?', confirmDeleteCommentAdmin: 'Delete comment? (admin)', confirmDeletePost: 'Delete post? (admin)', confirmDeleteOwnPost: 'Delete this post? This cannot be undone.', confirmLeaveNewPost: 'Post not saved. Leave?', promptTitle: 'Title', promptBody: 'Text',
  error: 'Error', errorPasswordsMatch: 'Passwords do not match', errorPasswordLength: 'Password: 8+ chars, upper, lower, special', errorEmailRequired: 'Enter email', errorEmailInvalid: 'Enter a valid email', successPasswordChanged: 'Password changed', successEmailChanged: 'Email changed. Check your inbox.',
  footerText: '@Bizz — platform for entrepreneurs to connect and get support.', feedComposerPrompt: 'What do you want to share?', footerRights: 'All rights reserved.', footerPrivacy: 'Privacy policy', privacyIntro: '@Bizz collects and processes user data in accordance with applicable law. We use data to run the platform, verification, and to communicate with you.',
  chatsTitle: 'Chats', chatsAdmin: 'Administration', chatsAdminDesc: 'Notifications: replies, comments on your posts, verification, friend requests.', chatsAdminNotes: 'Note for administration', chatsAdminNotesPlaceholder: 'Write a message or note...', chatsRecent: 'Recent', chatsGroups: 'Group chats', chatsCreateGroup: '+ Create group', chatsGroupTitle: 'Chat title', chatsSelectFriends: 'Select friends', chatsSearchFriend: 'Search by name or company...', chatsNoResults: 'No results', chatsRemoveMember: 'Remove', chatsFriends: 'Friends', chatsNoFriends: 'No friends yet. Add some in Friends.', chatsNoMessages: 'No messages yet. Be the first to write!', chatsYou: 'You', chatsMessagePlaceholder: 'Write a message...', chatsAI: 'AI Chat', chatsSoon: 'soon', chatsAISoon: 'AI chat will be available here soon.',
  notification_mention: 'You were mentioned in a comment', notification_comment_on_post: 'Comment on your post', notification_reply_to_comment: 'Reply to your comment', notification_verification_approved: 'Verification approved', notification_friend_request: 'Friend request', notification_registration: 'Welcome! Registration successful.', notification_message_reply: 'Reply to your message in chat',
  reactionMuzhik: 'dude!', reactionKoroleva: 'queen!', reactionRzhaka: 'lol', reactionFire: 'fire', reactionFu: 'yuck', reactionGrustno: 'sad', reactionBabki: 'making money', reactionHahaha: 'hahaha', reactionUseful: 'Useful',
  balance: 'balance', postPrice: 'Post price (currency)', postPriceHint: 'Only for «Useful» category. 0 = free post.', buyPost: 'Buy', profileBalance: 'Balance', adminAddBalance: 'Add currency', adminAddBalanceBtn: 'Add', balanceTopUpTitle: 'Top up balance', balanceTopUpHint: 'Top up your balance to buy paid posts.', balanceTopUpHintText: 'Enter number of coins. 1 coin = 1 ₽. Payment system will be connected later.', balanceTopUpAmount: 'Number of coins', balanceTopUpBuy: 'Buy', balanceTopUpMin: 'Minimum 1 coin', balanceTopUpSuccess: 'Balance topped up!',
  navSubscription: 'Subscription', subscriptionTitle: 'Unlimited subscription', subscriptionDesc: 'Read all posts with no limits. 2 free opens per month not enough? Get unlimited.', subscriptionPrice: 'Payment coming soon', subscriptionBuy: 'Subscribe', subscriptionOpen: 'Open', subscriptionOpensLeft: 'left', subscriptionConnectUnlimited: 'Get unlimited plan', subscriptionOutOfOpens: 'You have used all free opens this month. Get unlimited plan.', adminSubscriptionEnds: 'Subscription until', subscriptionBadge: 'Unlimited', subscriptionHeroTitle: 'Read everything. No limits.', subscriptionHeroDesc: 'Get access to hundreds of discussions from entrepreneurs — experience, insights, and solutions that work.', subscriptionBenefit1Title: 'Unlimited access', subscriptionBenefit1Text: 'open any post, anytime', subscriptionBenefit2Title: 'Exclusive experience', subscriptionBenefit2Text: 'ideas from those who already succeeded', subscriptionBenefit3Title: 'Community', subscriptionBenefit3Text: 'discuss and find like-minded people', subscriptionBenefit4Title: 'Groups', subscriptionBenefit4Text: 'create groups to communicate with entrepreneurs', subscriptionPopular: 'Popular choice', subscriptionPriceOld: '813 ₽', subscriptionPricePeriod: '/ month', subscriptionDiscount: '−15%', subscriptionMarketing: 'No free month — we value our platform and keep building it!', subscriptionActivated: 'Subscription activated for one month!', subscriptionNote: 'Payment coming soon.', subscriptionCtaText: 'Join entrepreneurs who are already growing their business with @Bizz', toastModerationTitle: 'Moderation', toastModerationText: 'Post saved as draft. Inappropriate words found: ',
  tourClose: 'Close', tourBack: 'Back', tourNext: 'Next', tourOf: 'of', tourFinish: 'Close',
  tourWelcomeTitle: 'Welcome to @Bizz!', tourWelcomeText: 'A quick tour of the interface: we\'ll show you the main sections and buttons.',
  tourStepLogoTitle: 'Home', tourStepLogoText: 'Logo — click to return to the feed.',
  tourStepNavTitle: 'Sections', tourStepNavText: 'Topics, favorites, subscription, and chats.',
  tourStepSidebarTitle: 'Sidebar', tourStepSidebarText: 'Post topics, trends, favorites, drafts, and «New post» button.',
  tourStepFeedTitle: 'Feed and publish', tourStepFeedText: 'Here is the feed of discussions. At the top — quick post composer.',
  tourStepProfileTitle: 'Profile', tourStepProfileText: 'Your name, balance, profile link, and sign out.',
  tourEndTitle: 'All set!', tourEndText: 'You can browse the feed or write your first post. Good luck!'
}
};

function getLang(){ try { var l = localStorage.getItem(LANG_KEY); return (l && I18N[l]) ? l : 'ru'; } catch(e){ return 'ru'; } }
function setLang(lang){ if(!I18N[lang]) return; try { localStorage.setItem(LANG_KEY, lang); } catch(e){} if(window.BizForum && window.BizForum.i18n) window.BizForum.i18n.currentLang = lang; }
function t(key){ var lang = getLang(); var s = (I18N[lang] && I18N[lang][key]) || (I18N.ru && I18N.ru[key]) || key; if(typeof s !== 'string') return key; return s; }
function tFormat(key, opts){ var s = t(key); if(opts) for(var k in opts) if(opts.hasOwnProperty(k)) s = s.replace(new RegExp('\\{' + k + '\\}', 'g'), opts[k]); return s; }
function getLocale(){ var lang = getLang(); return lang === 'en' ? 'en-US' : 'ru-RU'; }

function applyLang(){
var lang = getLang();
document.documentElement.lang = lang === 'en' ? 'en' : 'ru';
document.querySelectorAll('[data-i18n]').forEach(function(el){ var k = el.getAttribute('data-i18n'); if(k) el.textContent = t(k); });
document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el){ var k = el.getAttribute('data-i18n-placeholder'); if(k) el.placeholder = t(k); });
var sortSelect = document.getElementById('sort'); if(sortSelect && sortSelect.options.length >= 5){ sortSelect.options[0].text = t('feedSortRecommended'); sortSelect.options[1].text = t('feedSortNew'); sortSelect.options[2].text = t('feedSortHot'); sortSelect.options[3].text = t('feedSortComments'); sortSelect.options[4].text = t('feedSortViews'); }
var sortCat = document.getElementById('sort-cat'); if(sortCat && sortCat.options.length >= 5){ sortCat.options[0].text = t('feedSortRecommended'); sortCat.options[1].text = t('feedSortNew'); sortCat.options[2].text = t('feedSortHot'); sortCat.options[3].text = t('feedSortComments'); sortCat.options[4].text = t('feedSortViews'); }
if(window.dispatchEvent) window.dispatchEvent(new CustomEvent('bizforum:lang', { detail: { lang: lang } }));
}

window.BizForum = window.BizForum || {};
window.BizForum.i18n = { getLang: getLang, setLang: setLang, t: t, tFormat: tFormat, getLocale: getLocale, applyLang: applyLang, I18N: I18N };
window.t = t;
})();
